name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  github-release:
    name: Publish GitHub release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CHGLOG_VERSION: "0.15.4"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate version changelog
      run: |
        set -euo pipefail
        export BASE_URL="https://github.com/git-chglog/git-chglog/releases/download"
        export FILENAME="git-chglog_${CHGLOG_VERSION}_linux_amd64.tar.gz"
        curl -fsSL "${BASE_URL}/v${CHGLOG_VERSION}/${FILENAME}" |sudo tar xz --no-same-owner -C /usr/local/bin git-chglog
        git-chglog --config .github/chglog/config.yml --output CHANGELOG.md "${GITHUB_REF_NAME}"

    - name: Create GitHub release
      uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v0.1.15
      with:
        body_path: CHANGELOG.md

  docker-image:
    runs-on: ubuntu-latest
    needs: github-release
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0

      - name: Log in to Docker Hub registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: |
            docker.io/powerapi/hwpc-sensor
            ghcr.io/powerapi-ng/hwpc-sensor
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        id: build-and-push
        with:
          push: true
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_TYPE=Release
